recommendations = {
    "Apple___Apple_scab": "Apply fungicides like captan or myclobutanil. Rake and destroy fallen leaves to reduce overwintering spores.",
    "Apple___Black_rot": "Remove and destroy mummified fruit and dead wood. Apply fungicides during the growing season.",
    "Apple___Cedar_apple_rust": "Remove nearby juniper/red cedar hosts if possible. Apply fungicides like myclobutanil.",
    "Apple___healthy": "Your apple tree looks healthy! Maintain regular watering and fertilization.",
    "Blueberry___healthy": "Your blueberry plant looks healthy! Ensure acidic soil (pH 4.5-5.5).",
    "Cherry_(including_sour)___Powdery_mildew": "Apply sulfur or potassium bicarbonate. Prune to improve air circulation.",
    "Cherry_(including_sour)___healthy": "Your cherry tree looks healthy! Monitor for pests.",
    "Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot": "Plant resistant hybrids. Rotate crops. Apply fungicides if severe.",
    "Corn_(maize)___Common_rust_": "Plant resistant hybrids. Fungicides are rarely needed unless infection is early and severe.",
    "Corn_(maize)___Northern_Leaf_Blight": "Plant resistant hybrids. Rotate crops. Apply fungicides if necessary.",
    "Corn_(maize)___healthy": "Your corn looks healthy! Ensure adequate nitrogen.",
    "Grape___Black_rot": "Remove mummified berries. Apply fungicides like mancozeb or myclobutanil.",
    "Grape___Esca_(Black_Measles)": "Prune out infected wood. There is no cure; manage vine stress.",
    "Grape___Leaf_blight_(Isariopsis_Leaf_Spot)": "Apply fungicides. Improve air circulation.",
    "Grape___healthy": "Your grape vine looks healthy! Prune annually.",
    "Orange___Haunglongbing_(Citrus_greening)": "There is no cure. Remove infected trees to prevent spread. Control psyllid vectors.",
    "Peach___Bacterial_spot": "Plant resistant varieties. Apply copper sprays during dormancy.",
    "Peach___healthy": "Your peach tree looks healthy! Thin fruit for better size.",
    "Pepper,_bell___Bacterial_spot": "Use disease-free seeds. Apply copper sprays. Rotate crops.",
    "Pepper,_bell___healthy": "Your bell pepper plant looks healthy! Water regularly.",
    "Potato___Early_blight": "Apply fungicides like chlorothalonil. Rotate crops. Remove infected debris.",
    "Potato___Late_blight": "This is serious. Apply fungicides immediately. Destroy infected plants.",
    "Potato___healthy": "Your potato plant looks healthy! Hill soil around the base.",
    "Raspberry___healthy": "Your raspberry plant looks healthy! Prune old canes.",
    "Soybean___healthy": "Your soybean plant looks healthy! Monitor for pests.",
    "Squash___Powdery_mildew": "Apply neem oil or sulfur. Plant resistant varieties.",
    "Strawberry___Leaf_scorch": "Remove infected leaves. Apply fungicides if severe.",
    "Strawberry___healthy": "Your strawberry plant looks healthy! Mulch to keep fruit clean.",
    "Tomato___Bacterial_spot": "Use disease-free seeds. Apply copper sprays. Avoid overhead watering.",
    "Tomato___Early_blight": "Apply fungicides. Mulch to prevent soil splash. Rotate crops.",
    "Tomato___Late_blight": "Serious disease. Remove infected plants. Apply fungicides.",
    "Tomato___Leaf_Mold": "Improve air circulation. Apply fungicides like chlorothalonil.",
    "Tomato___Septoria_leaf_spot": "Remove lower infected leaves. Apply fungicides. Rotate crops.",
    "Tomato___Spider_mites Two-spotted_spider_mite": "Use insecticidal soap or neem oil. Increase humidity.",
    "Tomato___Target_Spot": "Apply fungicides. Improve air circulation.",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "Control whiteflies. Remove infected plants. Use resistant varieties.",
    "Tomato___Tomato_mosaic_virus": "Remove infected plants. Wash hands after handling tobacco products.",
    "Tomato___healthy": "Your tomato plant looks healthy! Stake or cage for support."
}

def get_recommendation(class_name):
    """Returns the recommendation for a given class name."""
    return recommendations.get(class_name, "No specific recommendation available. Please consult an agricultural expert.")
